version: '3.8'
services:
  postgres-pagos:
    image: postgres:15
    environment:
      POSTGRES_DB: pagos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pagos-db-data:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:latest
    command: >
      sh -c "
      bin/pulsar standalone --no-functions-worker --no-stream-storage
      "
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"

  api:
    build: .
    environment:
      PYTHONPATH: /app
      DB_HOST: postgres-pagos
      DB_PORT: 5432
      DB_NAME: pagos_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PULSAR_URL: pulsar://pulsar:6650
    ports:
      - "8090:8080"
    depends_on:
      - postgres-pagos
      - pulsar
    command: uvicorn main:app --host 0.0.0.0 --port 8080

volumes:
  pagos-db-data:
