from pydispatch import dispatcher
from modulos.referidos.dominio.eventos import VentaReferidaConfirmada, VentaReferidaRechazada
from modulos.referidos.aplicacion.handlers import HandlerReferidosIntegracion
from modulos.referidos.infraestructura.despachadores import Despachador

dispatcher.connect(HandlerReferidosIntegracion.handle_venta_referida_confirmada, signal=f'{VentaReferidaConfirmada.__name__}Integracion')
dispatcher.connect(HandlerReferidosIntegracion.handle_venta_referida_rechazada, signal=f'{VentaReferidaRechazada.__name__}Integracion')